
###this script should be in the folder scriptsCoNiTi

scriptsFolder=$PWD
cd ..

workDir=$PWD
echo "working folder is " $workDir


################################################################################
# Compiling code for fixing diff.cfg that WILL BE generated by ./mlp to make
# suitable for VASP, as it will not accept zero-concentrations.
################################################################################
cd $scriptsFolder
g++ fixing_cfgFiles.cpp # the output is a.out


################################################################################
# Generate the diff.cfg files using mlp
# You should ckeck if the previous VASP runnings did well!
################################################################################
module purge
module load mpi/openmpi-1.8.5_intel-15.0.2
module switch compiler_intel/15.0.2 compiler_intel/2017

cd $workDir/10_aftrActLearningWithRelaxedVasp/runVasp/
runVaspDir=$PWD
touch train2.cfg

file="$workDir/10_aftrActLearningWithRelaxedVasp/justPOSCARs/foldersToCreate"

while IFS= read -r line
do
  echo "file = " $line
  cd $runVaspDir/$line/

  ### creating diff.cfg using mlp:
  $workDir/mlpFolder/mlp convert-cfg OUTCAR diff.cfg --input-format=vasp-outcar >> outcar.txt

  ### a.out was compiled from fixing_cfgFiles.cpp to fix the diff.cfg file
  cp $scriptsFolder/a.out  .

  ### fixing diff.cfg file:
  cp diff.cfg  backup_diff.cfg
  ./a.out  # the fixed file is in diff_fixed.cfg
  mv diff_fixed.cfg  diff.cfg

  ### concatenating *.cfg files:
  cd $runVaspDir
  cat train2.cfg  $runVaspDir/$line/diff.cfg  >  tempFile.txt
  mv tempFile.txt train2.cfg
  echo $line

done <"$file"


################################################################################
# SECOND TRAINING !!!
################################################################################
cd $runVaspDir
cp train2.cfg  $workDir/8_trainingWithRelaxedVasp/
cd $workDir/8_trainingWithRelaxedVasp/

mv train.cfg train1.cfg
cat train1.cfg train2.cfg > temporal.cfg
mv temporal.cfg train.cfg


cat > "jobTraining_2" << FIN
#!/bin/bash
####################################
#SBATCH --time=03:00:00   # walltime
#SBATCH --ntasks=16   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=1024M   # memory per CPU core
#SBATCH -J "jobTraining_2"   # job name
#SBATCH --mail-user=carlos.leon.chinchay@gmail.com   # email address
#SBATCH --mail-type=FAIL
#SBATCH -p physics

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
module purge
module load mpi/openmpi-1.8.5_intel-15.0.2
module switch compiler_intel/15.0.2 compiler_intel/2017

##module purge
##module load compiler_intel/2017
##module load openblas/0.2.15
##module load gdb/7.9.1
##module load compiler_gnu/4.9.2
##module load mpi/openmpi-1.8.4_gnu-4.9.2


mpirun -n 16 $workDir/mlpFolder/mlp train pot.mtp train.cfg > training.txt
echo "Second training finished. Moving Trained.mtp_ to pot.mtp..."

mv Trained.mtp_ pot.mtp
$workDir/mlpFolder/mlp calc-grade pot.mtp train.cfg train.cfg temp1.cfg
####################################
FIN

sbatch jobTraining_2



###

